name: Deploy Hugo # 任君喜欢

on:
  push:
    branches:
      - master   # master 更新触发

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - name: Build 
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.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 }} # 填写你自己的 personal_token
          PUBLISH_BRANCH: master  # 推送到当前 master 分支
          PUBLISH_DIR: ./public  # hugo 生成到 public 作为跟目录
          commit_message: ${{ github.event.head_commit.message }}
